Remove application checks into executing function

diff --git a/src/am b/src/am
--- a/src/am
+++ b/src/am
@@ -3,21 +3,6 @@ VERSION="1.5.0"
 LOG="am-build.log"
 echo "Automated Make v${VERSION}"
 
-if ! hash make 2>/dev/null; then
-  echo "Make not found, please make sure its installed!"
-  exit 1
-fi
-
-if ! hash cmake 2>/dev/null; then
-  echo "CMake not found, please make sure its installed!"
-  exit 1
-fi
-
-if ! hash ninja 2>/dev/null; then
-  echo "Ninja not found, please make sure its installed!"
-  exit 1
-fi
-
 function print_help() {
   echo ""
   echo "AM is a build automation tool that uses Make, CMake and Ninja"
@@ -106,24 +91,31 @@ function log_cat() {
 }
 
 function check_git_submodules() {
-  echo "Checking if Git is installed .."
-  if ! hash git 2>/dev/null; then
-    echo "Git not found, cannot run check-git-submodules! Skipping ..."
-  else
-    echo "Checking for .gitmodules file"
-    if [ -e ".gitmodules" ]; then
-      echo ".gitmodules found, initializing modules"
-      git submodule init >> $LOG
-      check_error
-      echo "Updating Git Modules"
-      git submodule update >> $LOG
-      check_error
-      echo "Finished"
+  echo "Checking for .gitmodules file"
+  if [ -e ".gitmodules" ]; then
+    echo ".gitmodules found, checking for git"
+
+    if ! hash git 2>/dev/null; then
+      echo "Git not found, please make sure its installed!"
+      exit 1
     fi
+
+    echo "Initializing modules"
+    git submodule init >> $LOG
+    check_error
+    echo "Updating Git Modules"
+    git submodule update >> $LOG
+    check_error
+    echo "Finished"
   fi
 }
 
 function run_ninja() {
+  if ! hash ninja 2>/dev/null; then
+    echo "Ninja not found, please make sure its installed!"
+    exit 1
+  fi
+
   echo "Running Ninja"
   echo "========= Running Ninja =========" >> $LOG
   ninja $ARGS >> $LOG
@@ -131,6 +123,11 @@ function run_ninja() {
 }
 
 function run_make() {
+  if ! hash make 2>/dev/null; then
+    echo "Make not found, please make sure its installed!"
+    exit 1
+  fi
+
   echo "Running Make"
   echo "========= Running Make =========" >> $LOG
   make $ARGS >> $LOG
@@ -138,6 +135,11 @@ function run_make() {
 }
 
 function run_cmake() {
+  if ! hash cmake 2>/dev/null; then
+    echo "CMake not found, please make sure its installed!"
+    exit 1
+  fi
+
   echo "Running Cmake"
   echo "========= Running CMake =========" >> $LOG
   cmake $CARGS .. >> $LOG
